logging:
  level: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nix
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        hbm2ddl:
          import_files:
  application:
    name: '@project.artifactId@'
info:
  version: '@project.version@'
# swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /api/docs